REQUEST:

POST /api/v3/convert HTTP/2
Host: ii.ymcdn.org
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
Accept: */*
Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://pt1.greenconvert.net/
Content-Type: multipart/form-data; boundary=---------------------------9131189462905799011940241167
Content-Length: 537
Origin: https://pt1.greenconvert.net
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Priority: u=0
Te: trailers

-----------------------------9131189462905799011940241167
Content-Disposition: form-data; name="id"

556e849ce8ae4447932c20813dfe5a3a
-----------------------------9131189462905799011940241167
Content-Disposition: form-data; name="format"

256k
-----------------------------9131189462905799011940241167
Content-Disposition: form-data; name="type"

direct
-----------------------------9131189462905799011940241167
Content-Disposition: form-data; name="s"

false
-----------------------------9131189462905799011940241167--


RESPONSE:

HTTP/2 200 OK
Date: Tue, 01 Oct 2024 21:42:24 GMT
Content-Type: application/json; charset=UTF-8
Vary: Accept-Encoding
X-Powered-By: PHP/7.4.33
Set-Cookie: PHPSESSID=tqgv3nis7hlpvpql7vcog3hha6; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: upgrade-insecure-requests
Access-Control-Allow-Origin: https://pt1.greenconvert.net
Strict-Transport-Security: max-age=31536000
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cf-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=0x6AGc32vgAer4MZ%2B3m84zOnjYoT0AiWjBRhV8SXKRUlnfTudzNeUuQYcMSwcPyO%2FZFCovA1Rf3Godf5R%2Bl5vXL%2BTn0HJlXc6qh7zUN4L75AB6RR8toiU6uTsWjktdo%3D"}],"group":"cf-nel","max_age":604800}
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
Cf-Ray: 8cbf9f530b59ae75-GRU

{"status":true,"type":"sound"}