REQUEST:

POST /api/v3/detail HTTP/2
Host: ii.ymcdn.org
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
Accept: */*
Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://pt1.greenconvert.net/
Content-Type: multipart/form-data; boundary=---------------------------202208935813105107162010862666
Content-Length: 671
Origin: https://pt1.greenconvert.net
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Te: trailers

-----------------------------202208935813105107162010862666
Content-Disposition: form-data; name="id"

556e849ce8ae4447932c20813dfe5a3a
-----------------------------202208935813105107162010862666
Content-Disposition: form-data; name="format"

256k
-----------------------------202208935813105107162010862666
Content-Disposition: form-data; name="type"

sound
-----------------------------202208935813105107162010862666
Content-Disposition: form-data; name="readType"

sound
-----------------------------202208935813105107162010862666
Content-Disposition: form-data; name="direct"

direct
-----------------------------202208935813105107162010862666--

RESPONSE:

HTTP/2 200 OK
Date: Tue, 01 Oct 2024 21:42:42 GMT
Content-Type: application/json; charset=UTF-8
Vary: Accept-Encoding
X-Powered-By: PHP/7.4.33
Set-Cookie: PHPSESSID=5b4aj0eahvn2f2g261uf2mb0h5; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: upgrade-insecure-requests
Access-Control-Allow-Origin: https://pt1.greenconvert.net
Strict-Transport-Security: max-age=31536000
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cf-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=gnatIRYnGSLmN3RLlG1HXj3OFwpCRe1GtuXKBcXthsDVqoWZmk56bDOZ1F8ybzz1oZOE2vmz3PpjmfSBJRaSVXcYaEiaDzSsLrffRYQjCj3MPk%2FA6CD5Q8UEvJnrbkw%3D"}],"group":"cf-nel","max_age":604800}
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
Cf-Ray: 8cbf9fc1cdfd02ee-GRU

{"status":1,"loaderId":1,"fileUrl":["https:\/\/dl.ymcdn.org\/v2\/556e849ce8ae4447932c20813dfe5a3a\/uYYgJ9gRpVs?_l=Q29sb3NzZW5zZXMrRStTdWFzK0xpbmhhcytkZStBbW9yKy0rVmVycyVDMyVBM28rTWV0YWwrJTI4RmhvcCtNdXNpYyUyOQ==&_t=KFNakZDkEiQ=",null],"fileName":"Colossenses E Suas Linhas de Amor - Vers\u00e3o Metal (Fhop Music).mp3","fId":"256k"}